### ISSUE TITLE
Documented class name

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-class#1]
I don't think `DefineClass` is a good name, we don't usually things based on what type they are. We wouldn't call `count`, `countInteger`. We didn't call `Observation`, `ObserationClass` or `ObservationConstructor`.

Some ideas:

* `Defined`
* `Definable`

> Note that this isn't about the package name, `can-define-class` is an action and fits with other packages we have.

cc @phillipskevin @justinbmeyer

**Comment by justinbmeyer** [comment]
The package name should match the canjs export name. Most packages do. 

Calling it class is a bit different here because it is intended to be inherited. One creates an observation from Observation. One created (through extend) a class from DefineClass. 

I’d make sure to list what the List/Array equivalent would be when brainstorming.

**Comment by matthewp** [comment]
What about `DefineObject` and `DefineArray`?

**Comment by matthewp** [comment]
Superseded by #55
